services:
  web:
    container_name: file_server
    build: .
    image: file_server_web
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
    ports:
      - 8000:8000

  # db:
  #   container_name: file_server_db
  #   image: postgres:15
  #   restart: always
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - .env.prod.db
  #   ports:
  #     - "5432:5432"

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
